POST https://node-do-zero-r3xu.onrender.com/videos
Content-Type: application/json

{
   "title": "Video teste",
   "description": "Testando o deploy",
   "duration": 180
}

###

GET https://node-do-zero-r3xu.onrender.com/videos

###

PUT https://node-do-zero-r3xu.onrender.com/videos/80d77e77-4388-4b8a-a00e-c3417d369cce
Content-Type: application/json

{
   "title": "Video UOU",
   "description": "Bom demaize",
   "duration": 230
}

###

DELETE https://node-do-zero-r3xu.onrender.com/videos/80d77e77-4388-4b8a-a00e-c3417d369cce